### ISSUE TITLE
installation is not possible

### ISSUE THREAD

**Issue by AnnieHy** [mebis-lp/moodle-mod_mootimeter#123]
Hi,

I´m not able to install mootimeter on Moodle Version 4.4.
Do I have to take anything into account with Moodle version 4.4?
![error](https://github.com/mebis-lp/moodle-mod_mootimeter/assets/75210531/a4010434-f797-478b-94d2-cdd0556b1623)
Thanks for a short reply!

**Comment by PhMemmel** [comment]
This looks like a relict from the early development. Patch will come soon. Thank you for reporting!

**Comment by PM84** [comment]
Is it possible that you want to upgrade from an early development version?
If so: We do not support this. A few months before the release of the module, we made a breaking change in the DB structure. We did not make these changes via update steps, but instead uninstalled and reinstalled the plugin. 
I would like to ask you to follow the same path.

**Comment by AnnieHy** [comment]
Hi,

no, first time trying to install, no update.
Tried it again and I can´t install the plugin, unfortunately.
Best wishes

**Comment by PM84** [comment]
Please checkout the latest Master and try to install the plugin again. Perhaps you have to uninstall the damaged version first.

**Comment by AnnieHy** [comment]
I had to uninstall and reinstall the plugin several times. After the third attempt with the master it worked. Thank you
