### ISSUE TITLE
Problem in webservice function for wordcloud

### ISSUE THREAD

**Issue by cre-eledia** [mebis-lp/moodle-mod_mootimeter#131]
Hello colleagues, 

i am not sure if you are already aware, but on Moodle Workplace 4.4.1 (probably on standard moodle too) opening the API documentation i get the following error:

![Screenshot at 2024-07-15 09-07-30](https://github.com/user-attachments/assets/712e9077-dc92-46a5-8381-1819acb78520)

If i remove wordcloud everythings fine again. Hope this helps, don't have time to dive deeper.

Best regards from eLeDia,
Christopher

P.S. We use mod_mootimeter, 0.3.2, 2024053100 - great plugin!

**Comment by PhMemmel** [comment]
Thank you very much for the feedback. I believe I spotted the error. Should be fixed soon.
