### ISSUE TITLE
0.1.0 (2023121101) does not load in Moodle 4.3

### ISSUE THREAD

**Issue by tmuras** [mebis-lp/moodle-mod_mootimeter#73]
I'm testing the version 0.1.0 (2023121101) uploaded to https://moodle.org/plugins/mod_mootimeter/versions

When creating new activity and creating it, the page does not finish loading:
![image](https://github.com/mebis-lp/moodle-mod_mootimeter/assets/695281/345e082f-543f-424f-a573-b72a5d61e37e)

The calls to http://localhost/moodle43/lib/ajax/service.php?sesskey=hYHijTlDWE&info=mod_mootimeter_get_pages_list return valid values:
[
	{
		"error": false,
		"data": {
			"code": 200,
			"string": "ok",
			"pagelist": "{\"pageid\":0,\"cmid\":\"13\",\"instance\":\"1\",\"isediting\":true,\"pagelisttime\":0}"
		}
	}
]

**Comment by tmuras** [comment]
![image](https://github.com/mebis-lp/moodle-mod_mootimeter/assets/695281/77771eb4-5c09-46a9-8754-4941c915b974)

**Comment by PM84** [comment]
@tmuras Fixes with some changes since january.
