### ISSUE TITLE
styles.css not specific enough and should not be listed in thirdpartyllbs.xml

### ISSUE THREAD

**Issue by danmarsden** [mebis-lp/moodle-mod_mootimeter#74]
in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

Styles like the ones defined here are incorrect:
https://github.com/mebis-lp/moodle-mod_mootimeter/blob/develop/styles.css#L44-L54

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code. 

You also list this file in the thirdpartylibs.xml file which is incorrect. There are other ways to ignore parts of the file if needed for codechecker, but hopefully you can fix that up anyway.

NOTE: the styles not being specific enough, and listing in the thirdpartylibs.xml file are blockers for plugins db approval.

**Comment by PM84** [comment]
Fixed with 77d4c6d65684d0f6ef84717c5676718cf02d7c3a
