### ISSUE TITLE
camel case in lang strings.

### ISSUE THREAD

**Issue by danmarsden** [mebis-lp/moodle-mod_mootimeter#76]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

**Comment by PM84** [comment]
Thanks for reporting this!
Fixed with 045133ffc78a097b673e5e6e3e60748daff6437d
