### ISSUE TITLE
Diagram still being rendered despite teacher has not allowed access

### ISSUE THREAD

**Issue by PhMemmel** [mebis-lp/moodle-mod_mootimeter#94]
Despite the teacher has not published the results yet the statistic still is being rendered partially to the user:

Pie chart:

![grafik](https://github.com/mebis-lp/moodle-mod_mootimeter/assets/65113153/3256ba6b-36db-457f-b8df-3bb42b52ea04)

Bar chart:

![grafik](https://github.com/mebis-lp/moodle-mod_mootimeter/assets/65113153/54ebcffb-554d-4553-848b-5a7d130170fb)

Horizontal bar chart:

![grafik](https://github.com/mebis-lp/moodle-mod_mootimeter/assets/65113153/84de6d59-b063-45c6-b2be-9216835dd406)

**Comment by PM84** [comment]
Fixed with 1636df328acefc7c9cf98168cfb0f093da771f22
