### ISSUE TITLE
Title input field loses focus on update

### ISSUE THREAD

**Issue by PhMemmel** [mebis-lp/moodle-mod_mootimeter#98]
To reproduce:

- Create wordcloud or quiz
- Add title, wait a moment for the title to update in the window left
- Try to add another word in the title -> bug: input field loses focus when there is an update

The input field to add words to the wordcloud also loses focus

**Comment by PM84** [comment]
Fixed with c6d5485d6b95ba62f899d6c751983f3c8833233f
